@startuml
package "Prerequisites" #Bisque {
        rectangle "Python Intro" as python #White
        rectangle "Numpy & Linalg" as numpy #White
        rectangle "Classical ML/DL" as ml #White
}

package "Quantum Computing" as qci #Bisque {
        rectangle "Qubit" as qubit #Green
        rectangle "Gates" as gates #Green
        rectangle "Physics of qubit" as physq #Red
        rectangle "Mixed Stated" as mixed #Yellow
        rectangle "Grover" as grover #Yellow
        rectangle "Shor" as shor #Red
}

package "NISQ Hardware" #Bisque {
        rectangle "Hardware reivew" as review #Green
        rectangle "Perspectives in NISQ-era" as nisq #Green
}

package "Programming QC" #Bisque {
        rectangle "PennyLane" as pennylane #Green
        rectangle "Qiskit & Aqua" as qiskit #Yellow
        rectangle "Cirq & TFQ" as cirq #Yellow
}

package "VQC" #Bisque {
        rectangle "VQC" as vqc #Green
        rectangle "VQC as kernels" as kernelvqc #Yellow
        rectangle "Universality of VQC" as univvqc #Red
}

package "Gradients" #Bisque {
        rectangle "Gradients" as grad #Green
        rectangle "High-order gradients" as hograd #Yellow
        rectangle "QNG" as qng #Red
}

package "Classification" #Bisque {
        rectangle "VQC classification" as vqcc #Green
        rectangle "Barren plateaus" as barren #Yellow
        rectangle "Data encoding" as encoding #Yellow
}

package "Quantum SVM" #Bisque {
        rectangle "Hybrid SVM" as hsvm #Green
        rectangle "Classical SVM math" as csvm #Yellow
        rectangle "SVM with Grover" as gsvm #Red
}

package "Problems for QML" #Bisque {
        rectangle "Combinatorial Optimization" as copt #Green
        rectangle "Quantum\nMany-Body physics" as qmbp #Red
        rectangle "Quantum Chemistry" as qchem #Red
}

package "VQE" #Bisque {
        rectangle "VQE" as vqe #Green
        rectangle "Adaptive VQE" as avqe #Yellow
        rectangle "Layered VQC" as lvqe #Yellow
        rectangle "UUC anzatz" as uuc #Red
}

package "QAOA" #Bisque {
        rectangle "QAOA" as qaoa #Green
        rectangle "Cost/Mixed Hamiltonians" as hams #Yellow
}

package "D-Wave" #Bisque {
        rectangle "D-Wave & Sampling" as dwave #Green
        rectangle "Probabilistic Learning\n with D-Wave" as probml #Red
}

package "Jobs and Perspectives" as jobs #Bisque {
        rectangle "Academic positions" as academic #White
        rectangle "Industrial positions" as industrial #White
}

package "Advanced Topics" as adv #Bisque {
        rectangle "SotA review" as sota #Green
        rectangle "Qauntum RL" as qrl #Yellow
        rectangle "Advanced QRL" as aqrl #Red
        rectangle "CV quantum computers" as svqc #Red
        rectangle "LSTM VQC" as lstm #Yellow
        rectangle "Convolutional VQC" as convvqc #Yellow
}


python --> qubit
numpy --> qubit
ml --> qubit

qubit --> gates
qubit -> physq
mixed <- qubit
gates -> grover
shor <- gates

gates --> review
review -> nisq

gates --> pennylane
cirq <- pennylane
pennylane -> qiskit

pennylane --> vqc
kernelvqc <- vqc
vqc -> univvqc

vqc --> grad
qng <- grad
grad -> hograd

grad --> vqcc
barren <- vqcc
vqcc -> encoding

vqcc --> hsvm
csvm <- hsvm
hsvm -> gsvm

hsvm --> copt
qmbp <- copt
copt -> qchem

copt --> vqe
uuc <- vqe
vqe -> avqe
avqe -> lvqe

copt --> qaoa
qaoa -> hams

qaoa --> dwave
vqe --> dwave
dwave -> probml

dwave --> jobs

dwave -->adv
qrl --> aqrl

@enduml
