@startuml
package "Week 1" {
        package "Introduction" #Bisque {
                rectangle "Quantum Computers, Bitcoin and Quantum Advantage" as intro1 #14D2EF
        }

        package "Prerequisites" #Bisque {
                rectangle "Python Intro" as python_intro #14D2EF
                rectangle "Linalg & Numpy" as linalg_numpy_intro #14D2EF
                rectangle "ML Intro" as ml_intro #14D2EF
        }
}

intro1 --> python_intro
intro1 --> linalg_numpy_intro
intro1 --> ml_intro

package "Week 2" {
        package "Quantum Computing" as qci #Bisque {
                rectangle "Qubit" as qubit #40B464
                rectangle "Gates" as gates #40B464
                rectangle "Mixed Stated" as mixed #FFC864
        }

        package "Programming QC" #Bisque {
                rectangle "Frameworks Overview" as frameworks_overview #40B464
                rectangle "PennyLane" as pennylane #40B464
                rectangle "Cirq & TFQ" as cirq_tfq #FFC864
                rectangle "Qiskit" as qiskit #FFC864
        }
}

python_intro --> qubit
linalg_numpy_intro --> qubit
ml_intro --> qubit

qubit --> gates
qubit -> mixed

gates --> frameworks_overview
frameworks_overview --> pennylane
cirq_tfq <- frameworks_overview
frameworks_overview -> qiskit

package "Week 3" {
        package "Basic Quantum Algorithms" as qalgo #Bisque {
                rectangle "Quantum Algorithms Overview" as quantum_algorithms_overview #40B464
                rectangle "Deutsch" as deutsch #40B464
                rectangle "Quantum Teleportation" as quantum_teleportation #40B464
                rectangle "Superdense coding" as superdense_coding #40B464
                rectangle "Grover" as grover #FFC864
                rectangle "Simon" as saimon #FFC864
        }

}

pennylane --> quantum_algorithms_overview

quantum_algorithms_overview --> deutsch
quantum_algorithms_overview -> grover
saimon <- quantum_algorithms_overview

deutsch -> quantum_teleportation
quantum_teleportation --> superdense_coding

package "Week 4" {

        package "NISQ Hardware" #Bisque {
                rectangle "Hardware Overview" as hardware_overview #40B464
                rectangle "Superconducting qubits" as superconducting_qubits #E0535C
        }

        package "Quantum ML" #Bisque {
                rectangle "QML General" as qml_general #40B464
                rectangle "HHL" as hhl #E0535C
                rectangle "Quantum KNN" as qknn #E0535C
        }

        package "VQC" #Bisque {
                rectangle "VQC" as vqc #40B464
        }

}

superdense_coding --> hardware_overview
hardware_overview -> superconducting_qubits

hardware_overview --> qml_general

qml_general -> hhl
qknn <- qml_general

qml_general --> vqc

package "Week 5" {

        package "Gradients" #Bisque {
                rectangle "Gradients" as gradients #40B464
                rectangle "High-Order gradients" as high_gradients #FFC864
        }

        package "Quantum SVM" #Bisque {
                rectangle "Hybrid SVM" as hybrid_svm #40B464
                rectangle "Classical SVM" as classical_svm #FFC864
        }

        package "Quantum Neural Networks" #Bisque {
                rectangle "QNN" as quantum_nn #40B464
'                rectangle "Barren plateaus" as barren #FFC864
                rectangle "Convolutional VQC" as quantum_cnn #40B464
        }
}

vqc --> gradients
gradients -> high_gradients

gradients --> hybrid_svm
hybrid_svm -> classical_svm

hybrid_svm --> quantum_nn
quantum_nn -> quantum_cnn

package "Week 6" {
        package "Problems for QML" #Bisque {
                rectangle "Ising model" as ising #40B464
                rectangle "Advanced Ising" as ising_advanced #FFC864
                rectangle "Combinatorial Optimization" as combinatorial_optimization #40B464
                rectangle "Quantum Chemistry" as quantum_chemistry #40B464
                rectangle "Quantum Chemistry Advanced" as quantum_chemistry_advanced #FFC864
        }
}

quantum_nn --> ising
quantum_nn --> combinatorial_optimization
quantum_nn --> quantum_chemistry

ising_advanced <- ising
quantum_chemistry_advanced <- quantum_chemistry

package "Week 7" {
        package "From problems to QML" #Bisque {
                rectangle "NP-problems as Ising model" as np_problem_ising #40B464
                rectangle "Jordan-Wigner transformation" as jordan_wigner #FFC864
                rectangle "QUBO" as qubo #FFC864
                rectangle "Eigenvalues problem" as eigenvalues_problem #40B464
        }

}

combinatorial_optimization --> np_problem_ising
ising --> np_problem_ising
ising --> jordan_wigner
quantum_chemistry --> jordan_wigner

np_problem_ising --> eigenvalues_problem
jordan_wigner <- np_problem_ising
np_problem_ising --> qubo
jordan_wigner --> eigenvalues_problem

package "Week 8" {
        package "VQE" #Bisque {
                rectangle "VQE" as vqe #40B464
                rectangle "TSP with VQE" as tsp_with_vqe #FFC864
        }

        package "D-Wave" #Bisque {
                rectangle "D-Wave & Sampling" as d_wave #40B464
                rectangle "Quantum & Classic Annealers" as q_c_annealers #FFC864
        }

        package "QAOA" #Bisque {
                rectangle "QAOA" as qaoa #40B464
        }

        package "Jobs and Perspectives" as jobs #Bisque {
                rectangle "Academic & Industrial Positions" as academic_industrial #White
        }
}

eigenvalues_problem --> vqe
eigenvalues_problem --> d_wave

vqe --> tsp_with_vqe

q_c_annealers <- d_wave
d_wave --> qaoa

qaoa --> academic_industrial

@enduml
