@startuml
rectangle "<latex>\mathbf{X}</latex>" as x #40B464
rectangle "<latex>\hat{U}(X)</latex>" as ux #E0535C
rectangle "<latex>\hat{U}(\theta)</latex>" as ut #E0535C
rectangle "<latex>\hat{M}</latex>" as measure #E0535C
rectangle "<latex>L(y, \hat{y})</latex>" as loss #40B464
rectangle "<latex>\frac{dL}{d\theta}</latex>" as grad #40B464
rectangle "<latex>\theta_{n+1} = \theta_n - \gamma G</latex>" as upd #40B464

x --> ux
ux --> ut
ut --> measure
measure --> loss
loss -> grad
upd <-- grad
ut <- upd
@enduml
