@startuml
rectangle "Initialization" as init #40B464
rectangle "<latex>\hat{U}_1</latex>" as unit1 #FFC864
rectangle "<latex>\hat{U}_2</latex>" as unit2 #FFC864
rectangle "<latex>\hat{U}_3</latex>" as unit3 #FFC864
rectangle "Measurements" as measure #648CB4

init --> unit1
unit1 -> unit2
unit2 -> unit3
unit3 --> measure
@enduml
