@startuml

skinparam {
  BackgroundColor Black
  ArrowColor White
}

package "Week 1" #Sienna {
        package "Introduction" #DarkGoldenRod {
                rectangle "Quantum Computers, Bitcoin and Quantum Advantage" as intro #DeepSkyBlue
        }

        package "Prerequisites" #DarkGoldenRod {
                rectangle "Python Intro" as python_intro #DeepSkyBlue
                rectangle "Linalg & Numpy" as linalg_numpy_intro #DeepSkyBlue
                rectangle "ML Intro" as ml_intro #DeepSkyBlue
        }
}

intro --> python_intro
intro --> linalg_numpy_intro
intro --> ml_intro

package "Week 2" #Sienna {
        package "Quantum Computing" as qci #DarkGoldenRod {
                rectangle "Qubit" as qubit #Green
                rectangle "Gates" as gates #Green
                rectangle "Mixed States" as mixed #Gold
        }

        package "Programming QC" #DarkGoldenRod {
                rectangle "Frameworks Overview" as frameworks_overview #Green
                rectangle "PennyLane" as pennylane #Green
                rectangle "Cirq & TFQ" as cirq_tfq #Gold
                rectangle "Qiskit" as qiskit #Gold
        }
}

python_intro --> qubit
linalg_numpy_intro --> qubit
ml_intro --> qubit

qubit --> gates
qubit -> mixed

gates --> frameworks_overview
frameworks_overview --> pennylane
cirq_tfq <- frameworks_overview
frameworks_overview -> qiskit

package "Week 3" #Sienna {
        package "Basic Quantum Algorithms" as qalgo #DarkGoldenRod {
                rectangle "Quantum Algorithms Overview" as quantum_algorithms_overview #Green
                rectangle "Deutsch" as deutsch #Green
                rectangle "Quantum Teleportation" as quantum_teleportation #Green
                rectangle "Superdense coding" as superdense_coding #Green
                rectangle "Grover" as grover #Gold
                rectangle "Simon" as saimon #Gold
        }

}

pennylane --> quantum_algorithms_overview

quantum_algorithms_overview --> deutsch
quantum_algorithms_overview -> grover
saimon <- quantum_algorithms_overview

deutsch -> quantum_teleportation
quantum_teleportation --> superdense_coding

package "Week 4" #Sienna {

        package "NISQ Hardware" #DarkGoldenRod {
                rectangle "Hardware Overview" as hardware_overview #Green
                rectangle "Superconducting qubits" as superconducting_qubits #Brown
        }

        package "Quantum ML" #DarkGoldenRod {
                rectangle "QML General" as qml_general #Green
                rectangle "HHL" as hhl #Brown
                rectangle "Quantum KNN" as qknn #Brown
        }

        package "VQC" #DarkGoldenRod {
                rectangle "VQC" as vqc #Green
        }

}

superdense_coding --> hardware_overview
hardware_overview -> superconducting_qubits

hardware_overview --> qml_general

qml_general -> hhl
qknn <- qml_general

qml_general --> vqc

package "Week 5" #Sienna {

        package "Gradients" #DarkGoldenRod {
                rectangle "Gradients" as gradients #Green
                rectangle "High-Order gradients" as high_gradients #Gold
        }

        package "Quantum SVM" #DarkGoldenRod {
                rectangle "Hybrid SVM" as hybrid_svm #Green
                rectangle "Classical SVM" as classical_svm #Gold
        }

        package "Quantum Neural Networks" #DarkGoldenRod {
                rectangle "QNN" as quantum_nn #Green
'                rectangle "Barren plateaus" as barren #Gold
                rectangle "Convolutional VQC" as quantum_cnn #Green
        }
}

vqc --> gradients
gradients -> high_gradients

gradients --> hybrid_svm
hybrid_svm -> classical_svm

hybrid_svm --> quantum_nn
quantum_nn -> quantum_cnn

package "Week 6" #Sienna {
        package "Problems for QML" #DarkGoldenRod {
                rectangle "Ising model" as ising #Green
                rectangle "Advanced Ising" as ising_advanced #Gold
                rectangle "Combinatorial Optimization" as combinatorial_optimization #Green
                rectangle "Quantum Chemistry" as quantum_chemistry #Green
                rectangle "Quantum Chemistry Advanced" as quantum_chemistry_advanced #Gold
        }
}

quantum_nn --> ising
quantum_nn --> combinatorial_optimization
quantum_nn --> quantum_chemistry

ising_advanced <- ising
quantum_chemistry_advanced <- quantum_chemistry

package "Week 7" #Sienna {
        package "From problems to QML" #DarkGoldenRod {
                rectangle "NP-problems as Ising model" as np_problem_ising #Green
                rectangle "Jordan-Wigner transformation" as jordan_wigner #Gold
                rectangle "QUBO" as qubo #Gold
                rectangle "Eigenvalues problem" as eigenvalues_problem #Green
        }

}

combinatorial_optimization --> np_problem_ising
ising --> np_problem_ising
ising --> jordan_wigner
quantum_chemistry --> jordan_wigner

np_problem_ising --> eigenvalues_problem
jordan_wigner <- np_problem_ising
np_problem_ising --> qubo
jordan_wigner --> eigenvalues_problem

package "Week 8" #Sienna {
        package "VQE" #DarkGoldenRod {
                rectangle "VQE" as vqe #Green
                rectangle "TSP with VQE" as tsp_with_vqe #Gold
        }

        package "D-Wave" #DarkGoldenRod {
                rectangle "D-Wave & Sampling" as d_wave #Green
                rectangle "Quantum & Classic Annealers" as q_c_annealers #Gold
        }

        package "QAOA" #DarkGoldenRod {
                rectangle "QAOA" as qaoa #Green
        }

        package "Jobs and Perspectives" as jobs #DarkGoldenRod {
                rectangle "Academic & Industrial Positions" as academic_industrial #Azure
        }
}

eigenvalues_problem --> vqe
eigenvalues_problem --> d_wave

vqe --> tsp_with_vqe

q_c_annealers <- d_wave
d_wave --> qaoa

qaoa --> academic_industrial

@enduml